name: Build wheels

on:
  workflow_dispatch:
  push:
    branches:
      - release-*
      - '*wheel*'  # must quote since "*" is a YAML reserved character; we want a string
    tags:
      - '*'
  pull_request:
    branches:
      - '*wheel*'  # must quote since "*" is a YAML reserved character; we want a string

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.buildplat[0] }}-${{ matrix.buildplat[1] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      matrix:
        buildplat:
          - [ ubuntu-20.04, manylinux_x86_64 ]
#          - [ ubuntu-20.04, musllinux_x86_64 ]
#          - [ macos-12, macosx_x86_64 ]
#          - [ windows-2022, win_amd64 ]
#          - [ windows-2022, win32 ]
        python: ["cp39", "cp310", "cp311", "cp312", "pp39"]
        exclude:
          # Don't build PyPy 32-bit windows
          - buildplat: [ windows-2019, win32 ]
            python: "pp39"
          - buildplat: [ ubuntu-20.04, musllinux_x86_64 ]
            python: "pp39"

    steps:
      - uses: actions/checkout@v3

      - name: 'Brew setup on macOS' # x-ref c8e49ba8f8b9ce
        if: ${{ startsWith(matrix.os, 'macos-') == true }}
        run: |
          set -e pipefail
          brew install automake pkg-config ninja

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.14.1
        env:
          CIBW_PRERELEASE_PYTHONS: True
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.buildplat[1] }}
        with:
          package-dir: "apis/python"
          output-dir: wheelhouse
          config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

# TODO: Needs support for pulling in the root directory
#  build_sdist:
#    name: Build source distribution
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Build sdist
#        run: pipx run build --sdist
#
#      - uses: actions/upload-artifact@v3
#        with:
#          path: dist/*.tar.gz
